# Generated by Django 5.1.6 on 2025-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('feedback_text', models.TextField()),
                ('image', models.ImageField(upload_to='feedback_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('feedback_text', models.TextField()),
                ('video', models.FileField(upload_to='feedback_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
